### ISSUE TITLE
Internal storage data left on the phone after uninstallation?

### ISSUE THREAD

**Issue by rkdarst** [NBerkel/HYKS#10]
@AnaTomomi reports that if the app is uninstalled, some files on internal storage can remain.  This needs to be checked

@AnaTomomi, can you tell me any special steps to reproduce this?

**Comment by AnaTomomi** [comment]
This has only happened in my phone (Nexus 5X, Android version 7.1.2).

How it happened:Uninstall the app. Check for the usual folders in the Android folder. Delete them. Reinstall the app and try to join the study, but I was already joined in one without even configuring). 
So there are no special steps. 
However after I started deleting the data from the app info screen, it never happened again.

**Comment by rkdarst** [comment]
Did you find this one day when we were together?  Can you check again?  I remember around that time I had an app version that was mixing up the internal and external storages, so it actually wasn't being stored where we thought it was.

Now, the data should be stored only in `Android/data/com.aware.plugin.hyks/files/AWARE`.  It is possible to make it use internal storage in the live version if we want, so no one can see the files at all.

**Comment by AnaTomomi** [comment]
Tried with the commited changes from f116aa4. 
I checked again. It is still happening. I can see the data in the folder Android/data/com.aware.plugin.hyks/files/AWARE. Here is what happens:

1. Uninstall the app --> successful
2. Check for AWARE and/or HYKS folders in internal storage (both, root and Android/data folder) --> none found
3. Install again the app -->successful
4. Open the app --> It seems it is already joined (synchronize button available, settings and join buttons inactive)
5. Tap synchronize button --> sends data, cross checked with koota, data is sent to koota successfully. 

I have only notice this on my phone. (Nexus 5, Android version 7.1.2)

**Comment by rkdarst** [comment]
OK, this is weird then.  For me, uninstalling deletes the
Android/data/com.aware.plugin.hyks folder automatically, and then when
I reinstall it is in the default state.  I uninstall by dragging to
"uninstall" from the app drawer screen, and install from android
studio.

I wonder if it's related to phone version?  Anyway, good report, we
will need to investigate.

-- 
| Richard Darst   -   http://rkd.zgib.net/   -   pgp 0xBD356740
| "Ye shall know the truth and -- the truth shall make you free"

**Comment by AnaTomomi** [comment]
@rkdarst tested with version 56c9706

issue solved

**Comment by rkdarst** [comment]
Closing, though we should keep checking to make sure it doesn't come back again.

**Comment by AnaTomomi** [comment]
It came back :( 
Tested on the most recent version. 
I can see the data in the folder Android/data/com.aware.plugin.hyks/files/AWARE. Here is what happens:

    Uninstall the app --> successful
    Check for AWARE and/or HYKS folders in internal storage (both, root and Android/data folder) --> none found
    Install again the app -->successful
    Open the app --> It seems it is already joined (synchronize button available, settings and join buttons inactive)
    Tap synchronize button --> sends data, cross checked with koota, data is sent to koota successfully.

**Comment by AnaTomomi** [comment]
@rkdarst @NBerkel I wasn't able to reopen the issue, but just letting you know it is still there

**Comment by AnaTomomi** [comment]
I still have problems with this, I tried different procedures, but this is the only one that has worked in deleting the ghost file/leave the study

1. Install and open the app --> success, but it is joined to a study
2. Do not turn on accessibility services.
3. Go to App info, force the app to stop and clear data.
4. Open the app again

This seems extremely specific, if one of the steps is not followed, this doesn't work...

**Comment by rkdarst** [comment]
Hm...

Does uninstalling and rebooting work in all cases?

If it is uninstalled (no special actions taken), and you wait a few
hours/days, and reinstall, is it still there?

My current hypothesis is something clever to prevent losing data if
you have it uninstalled for a short time.


On Tue, May 23, 2017 at 11:56:07PM -0700, AnaTomomi wrote:
> I still have problems with this, I tried different procedures, but this is the only one that has worked in deleting the ghost file/leave the study
> 
> 1. Install and open the app --> success, but it is joined to a study
> 2. Do not turn on accessibility services.
> 3. Go to App info, force the app to stop and clear data.
> 4. Open the app again
> 
> This seems extremely specific, if one of the steps is not followed, this doesn't work...

-- 
| Richard Darst   -   http://rkd.zgib.net/   -   pgp 0xBD356740
| "Ye shall know the truth and -- the truth shall make you free"
