### ISSUE TITLE
Pressing back from settings closes the app

### ISSUE THREAD

**Issue by rkdarst** [NBerkel/HYKS#20]
I think Ana reported this by email, but wen you go to the settings UI, when you click back the app closes.

**Comment by rkdarst** [comment]
The main HYKS activity in AndroidManifist.xml was defined with `android:noHistory="true"`.  @NBerkel, is this necessary?  Can we get equivalent functionality some other way?

**Comment by nielsvanberkel** [comment]
Thank you for identifying this. I don't think the noHistory is necessary, and have therefore now removed it in my latest push.
