### ISSUE TITLE
Join button "seems" not to work

### ISSUE THREAD

**Issue by AnaTomomi** [NBerkel/HYKS#21]
Device: Samsung Mega
Android Version 4.4.2
HYKS version: 56c9706

Installed the HYKS app successfully. Tap "join"--> no message is shown, the synchronize button does not appear.
Tap "Set schedule" --> no message shown.
Received new notification for answering PHQ9.--> worked

Result: The join button does no longer show a message and it may seem as it has not worked, although it joined successfully.

**Comment by rkdarst** [comment]
I haven't been able to reproduce this.  Maybe it's special about the ordering of how you do things?  Have you found any log exceptions related to it?

**Comment by rkdarst** [comment]
Has this been reproduced lately?  And if so, any log exceptions?

**Comment by AnaTomomi** [comment]
No log exemptions, the messages are not showing in my phone, but it actually does the stuff. Will close since it is annoying, but it is still functional
