### ISSUE TITLE
Aware not restarting if it is killed?

### ISSUE THREAD

**Issue by rkdarst** [NBerkel/HYKS#22]
I'm not entirely sure about the current state here, but:

`Plugin.java` is the only place `startAWARE` is called.  `Plugin.java` (`onStartCommand`) and `HYKS.java` (`onCreate`) have the intent broadcast that does `sendBroadcast(new Intent(Aware.ACTION_AWARE_PRIORITY_FOREGROUND))`.  The HYKS class is the main process.

I am wondering if things are set up so that the accessibility services and other things don't properly turn on again.  A person's phone had a memory cleaner which sometimes killed aware.  I noticed that the Applications accessibility service didn't restart, and also the foreground notification doesn't start again even if you reopen the HYKS app.  I am wondering if all of the app restarting methods we have don't trigger the required background services properly.

I will keep investigating.

**Comment by AnaTomomi** [comment]
Update: 
Phone: Nexus 5X
Android version: 7.1.2
HYKS version: 56c9706

has not killed the service even at times of inactivity. 

I will keep an eye on it.

**Comment by rkdarst** [comment]
Under developer options->running services, does the `applications` services (that says it's an accessibility service) ever stop?  This happened on talayeh's phone when the power saver killed it, I think.

**Comment by rkdarst** [comment]
@talayeha, with the latest versions, can you try:
* remove HYKS from the ignore list of the memory cleaner.  We want to see what happens when it is killed.
* Verify that the app gets killed
* Restart it, and see if the Applications accessibility service starts running again.

**Comment by rkdarst** [comment]
I *think* this is working with @talayeha's phone now.  At least it notices and requests accessibility  services again when the app restarts,  but the cleaner hasn't killed it (maybe because we have the foreground notification now)...

**Comment by AnaTomomi** [comment]
I tried on my phone today and it is still not working for me
