### ISSUE TITLE
Changes in OLO questions

### ISSUE THREAD

**Issue by AnaTomomi** [NBerkel/HYKS#23]
@rkdarst @NBerkel We received Feedback from the psychiatrists and there are some changes in the OLO questions:

1. The first questions are supposed to be likert scales. So the question that appears first needs to be:
<string name="olo_1">Juuri nyt tunnen itseni.</string>---> Description, same as before
    <string name="olo_1_1">iloiseksi</string>---> Likert scale
    <string name="olo_1_2">väsyneeksi</string>---> Likert scale
    <string name="olo_1_3">tyytyväiseksi</string>---> Likert scale
    <string name="olo_1_4">hermostuneeksi</string>---> Likert scale
    <string name="olo_1_5">rauhalliseksi</string>---> Likert scale
    <string name="olo_1_6">surulliseksi</string>---> Likert scale
    <string name="olo_1_7">innostuneeksi</string>---> Likert scale
<string name="olo_1_8">aktiiviseksi</string>---> Likert scale

Likert scale should be from 0 to 6 (7 stars)

2. Change in one of the "olo_2_4" answers. I see this change has been made in the HYKS/app/src/main/res/values/strings.xml. I don't know if this will immediately apply to the questionnaires. 

Thanks!

**Comment by rkdarst** [comment]
For (2), strings.xml is the right place to make the change.  Do you mean it's already been done?

I'm working on (1) now.  Is anyone else?

**Comment by rkdarst** [comment]
I am currently testing (1)

**Comment by rkdarst** [comment]
The star scale the app uses is built into Android, so it's either that or a lot more work.  It can have any number of stars, and we can distinguish no answer (0.0) from an answer (1.0-7.0).  Right now it doesn't require answers (I think none of the lickert scales require answers).

**Comment by AnaTomomi** [comment]
I don't quite understand what you mean.

All the likert scale questions (stars) should have 7 stars. 
The first star is supposed to represent "not at all" so it should have a score of "0". Right now it has a score of 1. 
The seventh star is supposed to represent "extremely" so it should have a score of "6". Right now it has a sore of 7.

We can either, tell the psychiatrist about this change and they will adapt, change this in Android (which I understand is hard), or subtract 1 from the score when it arrives to koota.

**Comment by rkdarst** [comment]
For the first page of olo questions, I've added something which stores `null` if the answer was zero, or `answer-1` otherwise.  Is there anywhere else this needs to be used besides that one page?

I'll let you know once it's tested and if this can be closed.

**Comment by rkdarst** [comment]
Are the changes to `olo_2_4` done now?

**Comment by rkdarst** [comment]
The `olo_2_4` is in your patch #29, so once we get that we are good.
