### ISSUE TITLE
Labels for stars in OLO

### ISSUE THREAD

**Issue by AnaTomomi** [NBerkel/HYKS#26]
There is been a new request: under the first and extreme star, there should be some labels representing the scale. We are still investigating what should be the correct labels. 
This has been done for the likert scale questions in the morning questionnaire.

I'll update as soon as we know the labels.

**Comment by AnaTomomi** [comment]
Add question "Oletko syönyt aterian" (answers "ei", "kyllä") before the question "oletko syönyt välipalan"

**Comment by rkdarst** [comment]
I see the question has been added.

**Comment by AnaTomomi** [comment]
Yes, this was missing




Thanks,




Get Outlook for Android







On Sat, May 20, 2017 at 12:03 AM +0300, "Richard Darst" <notifications@github.com> wrote:












I see the question has been added.

**Comment by rkdarst** [comment]
As for the labels under the stars: I haven't seen an easy way to do this yet.  The app uses standard android widgets with limited options.  I am sure that there is some easy way to put them there, however I don't know it.  I will investigate if I get enough time.

**Comment by rkdarst** [comment]
OK, found it in `esm_lickert.xml` in aware-core.  I can copy it from there tomorrow.

**Comment by rkdarst** [comment]
OK, added to the first page of Olo.  If it needs to be elsewhere, please do so or let me know.
