### ISSUE TITLE
Change PHQ9 frequency

### ISSUE THREAD

**Issue by AnaTomomi** [NBerkel/HYKS#27]
PHQ9 frequency should be every month, not every 15 days.

**Comment by rkdarst** [comment]
Changed to 4 weeks.  Should it also be limited to certain hours of the day, for example: only ask during hours of 8-18?  Right now it could ask once, anytime.

**Comment by AnaTomomi** [comment]
Between the hour set by the user




Get Outlook for Android







On Sat, May 20, 2017 at 12:11 AM +0300, "Richard Darst" <notifications@github.com> wrote:












Changed to 4 weeks.  Should it also be limited to certain hours of the day, for example: only ask during hours of 8-18?  Right now it could ask once, anytime.

**Comment by rkdarst** [comment]
Will be in next commit
