### ISSUE TITLE
Persistent notification?

### ISSUE THREAD

**Issue by rkdarst** [NBerkel/HYKS#3]
I was talking with @AnaTomomi, and we discussed making a persistent notification.  The very latest Aware has the ability to do this.  We aren't sure if it's useful, but we can check.

This happened in aware `4e130207`.  We need to figure out how to use it.  I think I need to rebase the HYKS changes onto the latest development, so assign this to me for now.

As an aside... the reason for this is that the HYKS app is dying quickly.  I wonder if it is properly using accessibility services to stay alive...

**Comment by AnaTomomi** [comment]
@rkdarst HYKS app keeps getting killed, despite the persistent notification. It always does when I am sleeping, so I am wondering if it has do to with long inactivity periods in the phone.

**Comment by rkdarst** [comment]
Ok, so...

Is the app added to the "battery optimization ignore list", like it used to
request a last week?  I wonder if that request isn't showing up anymore
because we use foreground mode now.

This is all I gon think of now.  This change was made 1-2 nights ago

**Comment by AnaTomomi** [comment]
AWARE is the one that request the "battery optimization list". HYKS has never asked this.
However I will add "do not optimize for battery" into the instructions. 

At least last night, the app did not get killed, although the battery was low (10%). (HYKS version 56c9706)

**Comment by AnaTomomi** [comment]
Phone: Sony
Android version: 7.0
HYKS version: f93b915

Persistent notification is not shown after joining the study and scheduler. The following process are not started: applications, ambient noise. 
After restart Applications process was started, the persistent notification appeared, but ambient noise is not.

**Comment by rkdarst** [comment]
We have notification now.  App being killed and not restarting is a separate matter.
