### ISSUE TITLE
Turning on/off questions

### ISSUE THREAD

**Issue by rkdarst** [NBerkel/HYKS#34]
This is about the ability to turn off questions after two weeks.

Here is my current proposal.  We make the `HYKS.setSchedule` method idempotent, so that it makes no changes if things are set up properly.  Then, we set a schedule to run it periodically, say, every hour.  Then, it can do what we need.  After 14 days, it can turn off the olo/morning/evening questions.  It can look at config variable status and do things based on that.

What do you think? 

This will depend on #35 which I am about to open.

**Comment by nielsvanberkel** [comment]
Sounds reasonable. Do you want to set a scheduler that expires 14 days from app 'installation', or check the timing in some other way?

**Comment by rkdarst** [comment]
OK, in my branch rkdarst/aware-client/master, I have an initail attempte at this.  In HYKS.java, I make save the app context in a static class attribute, which is used in the broadcast receiver.  I don't know what other problems this would make: will HYKS.java ever not run first?

**Comment by rkdarst** [comment]
Check for NULL in appContext

**Comment by rkdarst** [comment]
Indeed, our workaround for the static context doesn't work: this starts failing once the main app process goes into the background:

```
05-23 19:50:27.420 16363-16363/com.aware.plugin.hyks E/HYKS: HYKS_Settings_Runner was called and appContext was null.  Aborting.
```

So it has to be turned into a service of some sort.

**Comment by rkdarst** [comment]
This now works!
- Configuring start/end time on server and turning on/off daily and monthly questions
- Aware fetching configuration via the study check and updating settings
- The background settings check updating: on/off of daily questions and monthly questions (independently), and updating schedules if start and end time changes.
- The koota configuration works (however "default" does not always revert it back to the original state)
