### ISSUE TITLE
behavior questions OLO 4

### ISSUE THREAD

**Issue by AnaTomomi** [NBerkel/HYKS#40]
The answer to the question "...vähintään 30 min" should make the question "kuinka raskasta..." Appear or disappear.

Right now it's making the question "tämä piippaus.." dis/appear.

**Comment by rkdarst** [comment]
Should the "tämä piippaus.." always be visible?

I found the stuff about this.

**Comment by rkdarst** [comment]
Fixed now.

**Comment by AnaTomomi** [comment]
@rkdarst according to the last version available in the link, the question "tämä piippaus.." is not always visible. The question "kuinka raskasta..." is not dependent on the answer to "...vähintään 30 min"

**Comment by rkdarst** [comment]
"tämä piippaus"  --> make it always visible

"kuinka raskasta"  --> make it depend on "vähintään 30 min"

Are these what should be done?

**Comment by AnaTomomi** [comment]
"tämä piippaus" --> make it always visible YES

"kuinka raskasta" --> make it depend on "vähintään 30 min" WHEN THE ANSWER IS YES.

**Comment by rkdarst** [comment]
This should be fixed now, I think.
