### ISSUE TITLE
OLO question logic not working

### ISSUE THREAD

**Issue by AnaTomomi** [NBerkel/HYKS#41]
The question "juuri nyt olen yksin" should bring other questions depending on the answer. If I answer "kylla" then it brings the right question, however when answering "ei" it does not make the questions for "ei" appear. 
The strings/questions that should appear when answering "ei"  are olo_3_3_1_2, olo_3_3_1_3, olo_3_3_1_4, olo_3_3_1_5 in the string.xml file.

**Comment by rkdarst** [comment]
Found problem: olo.java hard coded a compariason with "Ei", and text changed to "En".  Will change to an ID check (I guess).

**Comment by rkdarst** [comment]
Fixed now.
