### ISSUE TITLE
OLO 1 xml first question stars not showing

### ISSUE THREAD

**Issue by AnaTomomi** [NBerkel/HYKS#42]
The stars for the question "juuri nyt tunnen itseni" are not shown/not available for answering.

**Comment by rkdarst** [comment]
It seems like "Juuri nyt tunnen itseni" is set up like instructions,
not a question, and has always been.  So this is a qusetion, not
instructions?

Also Olo instructions are not translated!


-- 
| Richard Darst   -   http://rkd.zgib.net/   -   pgp 0xBD356740
| "Ye shall know the truth and -- the truth shall make you free"

**Comment by rkdarst** [comment]
It turns out that that was actually the instructions.  I moved it to the instructions field.

Alternatively the instructions could be removed, since they are in every question too.  But I did the minimal change.
