### ISSUE TITLE
Battery optimization

### ISSUE THREAD

**Issue by rkdarst** [NBerkel/HYKS#43]
There should now be a notification to add an exemption for battery optimization.  Can you check if this improves things at all?

For our purposes, I think it may not matter that much for actual data collection.  However it might prevent killing some.

**Comment by AnaTomomi** [comment]
I checked but it doesn't. The app got killed in my cellphone. 
Battery doesn't seem to have a effect on my phone, as the app keeps running despite having the battery in less than 5%.
