### ISSUE TITLE
Check all Finnish translations

### ISSUE THREAD

**Issue by rkdarst** [NBerkel/HYKS#9]
- Make sure that all strings are in resources
- Send resources to a.m. to check translations, merge back in

Assignee: me, Ana

**Comment by rkdarst** [comment]
The following files can be checked for translations:

HYKS app:
  https://github.com/rkdarst/HYKS/blob/master/app/src/main/res/values/strings.xml

Aware client (not all of these need translating, mainly just the ones you see already translated.  Do check if anything else needs to be added to this file.):
  https://github.com/CxAalto/aware-client/blob/HYKS-live/aware-core/src/main/res/values/strings.xml

Questions which are at the top of 
  https://version.aalto.fi/gitlab/CxAalto/koota-research/blob/master/koota_hyks_2016.py

ping @AnaTomomi.  If you can give a.m. the files for editing in notepad or something like that, we can directly take the changes.

**Comment by rkdarst** [comment]
Ana, have you done this now?  Should I close this?

**Comment by AnaTomomi** [comment]
Don't. Some of the translations are missing.




It's useful for a reminder




Get Outlook for Android







On Sat, May 20, 2017 at 12:22 AM +0300, "Richard Darst" <notifications@github.com> wrote:












Ana, have you done this now?  Should I close this?

**Comment by rkdarst** [comment]
The following files can be checked for translations:

HYKS app:
  https://github.com/rkdarst/HYKS/blob/master/app/src/main/res/values/strings.xml

Aware client (not all of these need translating, mainly just the ones you see already translated.  Do check if anything else needs to be added to this file.):
  https://github.com/CxAalto/aware-client/blob/HYKS-live/aware-core/src/main/res/values/strings.xml

Questions which are at the top of 
  https://version.aalto.fi/gitlab/CxAalto/koota-research/blob/master/koota_hyks_2016.py

ping @AnaTomomi.  If you can give a.m. the files for editing in notepad or something like that, we can directly take the changes.
